export const districtData = {
  colombo: {
    name: "Colombo",
    slug: "colombo",
    province: "Western",
    image: "https://media.istockphoto.com/id/2150515282/photo/lotus-tower-colombo-sri-lanka.jpg?s=612x612&w=0&k=20&c=6vjhhOkfdEk94dj8L6OLL2FwcLwnvcbAtii50Ti-pwc=",
    description: "The bustling capital of Sri Lanka, Colombo is a vibrant mix of colonial heritage, modern development, and tropical charm. Known as the economic and cultural hub, it offers everything from historic landmarks to contemporary attractions.",
    highlights: [
      "Galle Face Green - iconic seafront promenade",
      "Old Parliament Building - colonial architecture",
      "Colombo National Museum - rich cultural collection",
      "Vihara Mahadevi Park - lush urban sanctuary",
      "Gangaramaya Temple - iconic Buddhist temple",
    ],
    population: "2.7M+",
    topAttraction: "Galle Face Hotel & Green",
    bestTimeToVisit: "December - March",
    localSpecialty: "Curry noodles, lamprais, and fresh seafood",
    hotels: 40,
    places: 35,
  },
  kandy: {
    name: "Kandy",
    slug: "kandy",
    province: "Central",
    image: "https://bokun.s3.amazonaws.com/c585f0ae-7fd6-4a80-9a5a-44465aba5007.jpeg?fl_progressive,h_507,w_900,q_5/",
    description: "Nestled in the highlands at 500m elevation, Kandy is the cultural heart of Sri Lanka. This ancient kingdom capital is surrounded by lush mountains and home to one of Buddhism's most sacred temples.",
    highlights: [
      "Temple of the Tooth - UNESCO World Heritage Site",
      "Kandy Lake - picturesque setting with legends",
      "Peradeniya Botanical Gardens - world-class gardens",
      "Kandy Esala Perahera - grand cultural festival",
      "Royal Palace Museum - historical artifacts",
    ],
    population: "1.5M+",
    topAttraction: "Temple of the Tooth Relic",
    bestTimeToVisit: "August (Esala Perahera festival)",
    localSpecialty: "Jaggery, puppetry crafts, and hill country tea",
    hotels: 32,
    places: 28,
  },
  galle: {
    name: "Galle",
    slug: "galle",
    image: "https://jetwingtravels.com/wp-content/uploads/2023/08/Galle-Fort.jpg",
    province: "Southern",
    description: "Famous for its majestic fort overlooking the Indian Ocean, Galle is a charming coastal town with rich maritime history. The Old Town within the fort is a UNESCO World Heritage Site with pristine beaches nearby.",
    highlights: [
      "Galle Fort - 300-year-old Dutch fortress",
      "Old Town - narrow streets and colonial buildings",
      "Unawatuna Beach - pristine sandy shores",
      "Jungle Beach - hidden tropical gem",
      "Galle International Cricket Stadium - historic venue",
    ],
    population: "0.8M+",
    topAttraction: "Galle Fort",
    bestTimeToVisit: "November - April",
    localSpecialty: "Fresh seafood, cinnamon, and traditional handicrafts",
    hotels: 28,
    places: 22,
  },
  negombo: {
    name: "Negombo",
    slug: "negombo",
    image: "https://img.freepik.com/premium-photo/beach-maldives_87394-39120.jpg?semt=ais_hybrid&w=740&q=80",
    province: "Western",
    description: "A charming beach town just 30km north of Colombo, Negombo blends tourism with authentic local culture. Known for its lagoon, fishing villages, and vibrant night life, it's a perfect coastal escape.",
    highlights: [
      "Negombo Lagoon - scenic water activities",
      "Negombo Beach - long sandy coastline",
      "Fish Markets - authentic local experience",
      "Dutch Canal - historic waterway",
      "Negombo Shrine - important pilgrimage site",
    ],
    population: "0.4M+",
    topAttraction: "Negombo Beach & Lagoon",
    bestTimeToVisit: "December - March",
    localSpecialty: "Fresh fish curry, shrimp paste, and beach seafood",
    hotels: 24,
    places: 18,
  },
  jaffna: {
    name: "Jaffna",
    slug: "jaffna",
    image: "https://d1bv4heaa2n05k.cloudfront.net/user-images/1533719149285/shutterstock-737423212_destinationMain_1533719167695.jpeg",
    province: "Northern",
    description: "The historic hub of Tamil culture and heritage in Sri Lanka, Jaffna offers unique cultural experiences, pristine islands, and archaeological wonders. A destination for those seeking authentic cultural immersion.",
    highlights: [
      "Jaffna Fort - military and historical significance",
      "Nallur Kandasamy Temple - important Hindu shrine",
      "Casuarina Beach - pristine northern shores",
      "Jaffna Islands - scenic boat tours",
      "Jaffna Public Library - architectural marvel",
    ],
    population: "0.9M+",
    topAttraction: "Jaffna Fort & Temple Tour",
    bestTimeToVisit: "April - September",
    localSpecialty: "Palm jaggery, fish curry, and coconut-based dishes",
    hotels: 18,
    places: 20,
  },
  nuwara_eliya: {
    name: "Nuwara Eliya",
    slug: "nuwara-eliya",
    image: "https://lakpura.com/cdn/shop/files/LK951R0000-10-E_4fb5ce5e-c060-481b-9ee3-429c7a3a7b72.jpg?v=1689939550&width=3840",
    province: "Central",
    description: "Sri Lanka's highest city at 1,868m, Nuwara Eliya is a cool mountain retreat with pleasant climate year-round. Famous for its tea gardens and colonial-era buildings, it's a nature lover's paradise.",
    highlights: [
      "Tea Plantations - scenic rolling green hills",
      "Gregory Lake - mountain lake and viewpoint",
      "Post Office - red colonial building",
      "Hakgala Botanical Gardens - alpine flora",
      "Pidurutalagala Peak - highest point with views",
    ],
    population: "0.4M+",
    topAttraction: "Tea Estate Tours & Gregory Lake",
    bestTimeToVisit: "May - September",
    localSpecialty: "Ceylon tea, strawberry jam, and mountain vegetables",
    hotels: 22,
    places: 16,
  },
  Mathale: {
    name: "Mathale",
    slug: "mathale",
    image: "https://thetravelshots.com/wp-content/uploads/2021/06/Sigiriya-e1624103657484.jpg",
    province: "North Central",
    description: "Home to the iconic Lion Rock, Sigiriya is one of Sri Lanka's most visited attractions. This ancient fortress rises dramatically from the plains and offers breathtaking views of the surrounding landscape.",
    highlights: [
      "Sigiriya Rock Fortress - 5th century marvel",
      "Mirror Wall - polished stone wall",
      "Ancient Frescoes - beautiful artwork",
      "Sigiriya Museum - historical context",
      "Surrounding Gardens - landscaped grounds",
    ],
    population: "0.3M+",
    topAttraction: "Sigiriya Rock Fortress",
    bestTimeToVisit: "November - March",
    localSpecialty: "Rice dishes, curry, and local honey",
    hotels: 16,
    places: 12,
  },
  matara: {
    name: "Matara",
    image: "https://www.steuartholidays.com/wp-content/uploads/2019/02/Beach-View-17-3.jpg",
    slug: "matara",
    province: "Southern",
    description: "A picturesque coastal town with a laid-back vibe, Matara offers beautiful beaches, water sports, and a rich maritime history. Perfect for those seeking relaxation and adventure in equal measure.",
    highlights: [
      "Matara Beach - golden sandy shores",
      "Star Fort - historical military structure",
      "Mirissa Beach - nearby paradise beach",
      "Dondra Lighthouse - scenic landmark",
      "Welikovda Beach - surfer's haven",
    ],
    population: "0.6M+",
    topAttraction: "Matara Beach & Mirissa",
    bestTimeToVisit: "November - April",
    localSpecialty: "Fresh fish curry, shrimp, and tropical fruits",
    hotels: 20,
    places: 16,
  },
  anuradhapura: {
    name: "Anuradhapura",
    image: "https://images.unsplash.com/photo-1548013146-72d72d408766?w=1200&h=700&fit=crop",
    slug: "anuradhapura",
    province: "North Central",
    description: "An ancient city with profound spiritual significance, Anuradhapura is Sri Lanka's oldest capital and home to some of the world's oldest continually worshipped temples. A pilgrimage destination for Buddhists.",
    highlights: [
      "Mahabodhi Temple - sacred temple complex",
      "Sacred Bodhi Tree - 2,300-year-old tree",
      "Twin Ponds - historical water structures",
      "Abhayagiri Dagoba - impressive stupa",
      "Ancient Monastery ruins - archaeological treasures",
    ],
    population: "0.8M+",
    topAttraction: "Sacred Bodhi Tree & Temples",
    bestTimeToVisit: "June - September",
    localSpecialty: "Rice curries, jaggery, and traditional sweets",
    hotels: 14,
    places: 18,
  },
  bathinda: {
    name: "Batticaloa",
    slug: "batticaloa",
    province: "Eastern",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=700&fit=crop",
    description: "An eastern coastal gem with a rich multicultural heritage, Batticaloa is known for its lagoons, Hindu temples, and lighthouse. A destination for those seeking authentic coastal experiences.",
    highlights: [
      "Batticaloa Lagoon - scenic water activities",
      "Batticaloa Lighthouse - historical landmark",
      "Thirukosandeeswara Temple - important shrine",
      "Kalladi Beach - pristine coastline",
      "Kalchavad Island - scenic exploration",
    ],
    population: "0.7M+",
    topAttraction: "Batticaloa Lagoon & Lighthouse",
    bestTimeToVisit: "May - September",
    localSpecialty: "Tuna curry, spicy rice dishes, and fresh seafood",
    hotels: 12,
    places: 14,
  },
  gampaha: {
    name: "Gampaha",
    slug: "gampaha",
    province: "Western",
    image: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1200&h=700&fit=crop",
    description: "A rapidly growing district with lush suburbs and coastal pockets. Close to Colombo with easy access to cultural and natural attractions.",
    highlights: ["Attanagalla Temple", "Nearby beaches", "Local markets", "Tea small-holdings", "Heritage sites"],
    population: "1.1M+",
    topAttraction: "Attanagalla Raja Maha Vihara",
    bestTimeToVisit: "December - March",
    localSpecialty: "Coconut-based snacks and seafood",
    hotels: 10,
    places: 8,
  },
  kalutara: {
    name: "Kalutara",
    slug: "kalutara",
    province: "Western",
    image: "https://images.unsplash.com/photo-1503264116251-35a269479413?w=1200&h=700&fit=crop",
    description: "A coastal district known for palm-lined beaches, the Kalutara Bodhiya and scenic river estuaries. Popular for laid-back beach stays.",
    highlights: ["Kalutara Beach", "Kalutara Bodhiya", "Rich coconut groves", "Karandeniya tea estates", "Local seafood markets"],
    population: "0.8M+",
    topAttraction: "Kalutara Bodhiya & Beach",
    bestTimeToVisit: "November - April",
    localSpecialty: "Crispy hoppers and fresh seafood",
    hotels: 14,
    places: 10,
  },
  hambantota: {
    name: "Hambantota",
    slug: "hambantota",
    province: "Southern",
    image: "https://images.unsplash.com/photo-1493558103817-58b2924bce98?w=1200&h=700&fit=crop",
    description: "A growing coastal district with wide sandy beaches, wildlife parks and historic ports. Emerging as a new tourism hub in the south-east.",
    highlights: ["Bundala Bird Sanctuary", "Hambantota Harbour", "Yala buffer areas", "Quiet beaches", "Cultural markets"],
    population: "0.5M+",
    topAttraction: "Bundala National Park",
    bestTimeToVisit: "May - September",
    localSpecialty: "Fresh crab dishes and coastal curries",
    hotels: 12,
    places: 9,
  },
  puttalam: {
    name: "Puttalam",
    slug: "puttalam",
    province: "North Western",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&h=700&fit=crop",
    description: "Known for its lagoons, salt flats and birdlife, Puttalam offers unique coastal landscapes and island hopping experiences.",
    highlights: ["Puttalam Lagoon", "Kalpitiya kite-surfing", "Dutch-era buildings", "Salt pans", "Bird sanctuaries"],
    population: "0.5M+",
    topAttraction: "Kalpitiya Peninsula",
    bestTimeToVisit: "June - September",
    localSpecialty: "Seafood curries and lagoon prawns",
    hotels: 8,
    places: 7,
  },
  kurunegala: {
    name: "Kurunegala",
    slug: "kurunegala",
    province: "North Western",
    image: "https://images.unsplash.com/photo-1499346030926-9a72daac6c63?w=1200&h=700&fit=crop",
    description: "An inland district with a mix of agriculture and historical sites; a gateway to cultural triangles and reservoir landscapes.",
    highlights: ["Ancient temples", "Reservoirs and lakes", "Market towns", "Rock outcrops", "Local crafts"],
    population: "0.7M+",
    topAttraction: "Ancient temples and reservoirs",
    bestTimeToVisit: "December - March",
    localSpecialty: "Rice-based dishes and village sweets",
    hotels: 9,
    places: 6,
  },
  polonnaruwa: {
    name: "Polonnaruwa",
    slug: "polonnaruwa",
    province: "North Central",
    image: "https://images.unsplash.com/photo-1544862175-5e2f6f7c0b3b?w=1200&h=700&fit=crop",
    description: "A UNESCO-listed ancient capital, Polonnaruwa contains well-preserved ruins, stupas, and monumental statues.",
    highlights: ["Ancient city ruins", "Gal Vihara rock carvings", "Royal Palace", "Irrigation tanks", "Cycling trails"],
    population: "0.3M+",
    topAttraction: "Polonnaruwa Ancient City",
    bestTimeToVisit: "May - September",
    localSpecialty: "Traditional rice and curry dishes",
    hotels: 11,
    places: 13,
  },
  trincomalee: {
    name: "Trincomalee",
    slug: "trincomalee",
    province: "Eastern",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=700&fit=crop",
    description: "Home to some of the Indian Ocean's best beaches and a deep-water natural harbour; Trinco is a hub for diving and island trips.",
    highlights: ["Nilaveli Beach", "Pigeon Island", "Koneswaram Temple", "Harbour views", "Diving sites"],
    population: "0.3M+",
    topAttraction: "Nilaveli & Pigeon Island",
    bestTimeToVisit: "May - September",
    localSpecialty: "Seafood and coastal specialties",
    hotels: 15,
    places: 14,
  },
  ampara: {
    name: "Ampara",
    slug: "ampara",
    province: "Eastern",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&h=700&fit=crop",
    description: "A varied district with lagoons, paddy fields and coastal stretches; known for quiet beaches and rural charm.",
    highlights: ["Lagoons and backwaters", "Local wildlife", "Coastal fishing villages", "Traditional festivals", "Rice paddies"],
    population: "0.4M+",
    topAttraction: "Coastal lagoons and rural tours",
    bestTimeToVisit: "May - September",
    localSpecialty: "Coconut-based sweets and seafood",
    hotels: 6,
    places: 6,
  },
  badulla: {
    name: "Badulla",
    slug: "badulla",
    province: "Uva",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&h=700&fit=crop",
    description: "A hill-country district with waterfalls, tea estates and scenic train routes — perfect for cool-climate escapes.",
    highlights: ["Dunhinda Falls", "Ravana Falls nearby", "Tea country drive", "Muthiyangana Temple", "Scenic viewpoints"],
    population: "0.3M+",
    topAttraction: "Hill-country waterfalls and tea estates",
    bestTimeToVisit: "May - September",
    localSpecialty: "Tea-infused desserts and hill snacks",
    hotels: 10,
    places: 9,
  },
  monaragala: {
    name: "Monaragala",
    slug: "monaragala",
    province: "Uva",
    image: "https://images.unsplash.com/photo-1499346030926-9a72daac6c63?w=1200&h=700&fit=crop",
    description: "Less-visited Uva district with access to wildlife reserves, rural villages and scenic highlands.",
    highlights: ["Yala-Mahiyangana routes", "Rural trails", "Reservoirs", "Local temples", "Nature walks"],
    population: "0.2M+",
    topAttraction: "Wildlife and rural nature trails",
    bestTimeToVisit: "May - September",
    localSpecialty: "Local grilled fish and rice dishes",
    hotels: 5,
    places: 4,
  },
  kilinochchi: {
    name: "Kilinochchi",
    slug: "kilinochchi",
    province: "Northern",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&h=700&fit=crop",
    description: "A northern district with a resilient recent history and quiet rural landscapes; a place for cultural reconnection.",
    highlights: ["Rural villages", "Local temples", "Lagoon shores", "Agricultural landscapes", "Community markets"],
    population: "0.2M+",
    topAttraction: "Lagoon and rural cultural visits",
    bestTimeToVisit: "April - September",
    localSpecialty: "Freshwater fish and local curries",
    hotels: 3,
    places: 3,
  },
  mullaitivu: {
    name: "Mullaitivu",
    slug: "mullaitivu",
    province: "Northern",
    image: "https://images.unsplash.com/photo-1503264116251-35a269479413?w=1200&h=700&fit=crop",
    description: "A sparsely populated coastal district with long beaches and a strong local culture; ideal for off-the-beaten-path visits.",
    highlights: ["Long quiet beaches", "Local fisheries", "Cultural sites", "Lagoon exploration", "Birdwatching"],
    population: "0.1M+",
    topAttraction: "Undisturbed beaches and lagoons",
    bestTimeToVisit: "April - September",
    localSpecialty: "Simple coastal fare and coconut dishes",
    hotels: 2,
    places: 2,
  },
  mannar: {
    name: "Mannar",
    slug: "mannar",
    province: "Northern",
    image: "https://images.unsplash.com/photo-1493558103817-58b2924bce98?w=1200&h=700&fit=crop",
    description: "An island-influenced district known for its sand dunes, baobab trees and historic links across the Palk Strait.",
    highlights: ["Mannar Island", "Baobab trees", "Historic churches", "Stilt fishing spots", "Salt pans"],
    population: "0.1M+",
    topAttraction: "Mannar Island & Baobab Trees",
    bestTimeToVisit: "April - September",
    localSpecialty: "Seafood and coastal snacks",
    hotels: 3,
    places: 3,
  },
  vavuniya: {
    name: "Vavuniya",
    slug: "vavuniya",
    province: "Northern",
    image: "https://images.unsplash.com/photo-1499346030926-9a72daac6c63?w=1200&h=700&fit=crop",
    description: "A district serving as a transport and service hub for the northern interior, with access to cultural and natural sites.",
    highlights: ["Gateway to northern districts", "Local markets", "Cultural temples", "Reservoirs", "Village tours"],
    population: "0.2M+",
    topAttraction: "Regional cultural visits",
    bestTimeToVisit: "April - September",
    localSpecialty: "Local sweets and rice dishes",
    hotels: 4,
    places: 5,
  },
  kegalle: {
    name: "Kegalle",
    slug: "kegalle",
    province: "Sabaragamuwa",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&h=700&fit=crop",
    description: "A hilly district famous for its rubber and gem mining, offering access to waterfalls and scenic drives.",
    highlights: ["Rubber estates", "Gem mining areas", "Waterfalls", "Hillside drives", "Village culture"],
    population: "0.4M+",
    topAttraction: "Waterfalls and gem markets",
    bestTimeToVisit: "December - March",
    localSpecialty: "Spicy hill-country curries",
    hotels: 6,
    places: 5,
  },
  ratnapura: {
    name: "Ratnapura",
    slug: "ratnapura",
    province: "Sabaragamuwa",
    image: "https://images.unsplash.com/photo-1503264116251-35a269479413?w=1200&h=700&fit=crop",
    description: "Known as the 'City of Gems', Ratnapura is surrounded by rainforests, waterfalls and tea estates — rich in natural resources.",
    highlights: ["Gem markets", "Sinharaja nearby", "Waterfalls", "Rainforest trails", "Tea estates"],
    population: "0.5M+",
    topAttraction: "Gem trading and nearby rainforests",
    bestTimeToVisit: "December - March",
    localSpecialty: "Spicy freshwater fish and local sweets",
    hotels: 7,
    places: 6,
  },
};

export function getDistrictInfo(slug: string) {
  const key = slug.replace("-", "_") as keyof typeof districtData;
  return districtData[key] || null;
}
